spring:
  profiles:
    include:
      - aws
      - credentials

server:
  port: 8080
  servlet:
    session:
      timeout: 30
  ssl:
    enabled: true
    key-alias: onechild
    key-store: onechild.pkcs12
    key-store-password: '@onechild@'
    key-password: '@onechild@'
    trust-store: ayotrust.pkcs12
    trust-store-password: '@onechild@'