cloud:
  aws:
    s3:
      bucket: s3cafe
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true #AWS CLI에서 aws configure list 정보를 반영할 건지 여부